### ISSUE TITLE
Accessing a resource with a snapshotDate() before it was available gives a cryptic error

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/AnnotationHub#11]
In the current 'devel' version of AnnotationHub, record "AH75194" exists
```
> hub = AnnotationHub()
snapshotDate(): 2019-10-25
> hub[["AH75194"]]
downloading 0 resources
loading from cache
                                                 AH75194 : 81940
"/Users/ma38727/Library/Caches/AnnotationHub/d90d285daf8e_81940"
```
but trying to access it from a snapshotDate() before it was available gives a cryptic message
```
> snapshotDate(hub) <- "2019-05-02"
> hub[["AH75194"]]
Error: Public
```
Also, I'm not sure why we're told `downloading 0 resources` or the internal information `AH75194 : 81940`, which makes it hard to know, from the return object, what the original, user-facing, AH id was (i.e., the name should just be `AH75194`).

**Comment by lshep** [comment]
I thought I got rid of the id information so I'll check on that implementation.

We do display the download information but maybe if it doesn't download anything we should change the message.

I don't think I ever tested trying to download a resource that is added after a snapshot date. I'll look into this. Thanks for reporting it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
