### ISSUE TITLE
Failed compilation with R-3.5.1

### ISSUE THREAD

**Issue by sk-sahu** [Bioconductor/AnnotationHub#14]
Error: 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
Aborted (core dumped)
```

sessioninfo()
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 19.10

Matrix products: default
BLAS/LAPACK: /home/sangram/miniconda3/envs/sig/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocManager_1.30.10

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1 
```

**Comment by lshep** [comment]
Could you please show the command you used when getting this ERROR and the complete output?

**Comment by mtmorgan** [comment]
This is a conda installation using an old R; a first step would be to use a current R and to ensure that you are following conda best practices, including installing packages via conda and not standard Bioconductor approaches. For help here, it would be very helpful to reproduce the problem on a non-conda installation.

**Comment by sk-sahu** [comment]
Thank you for your replies. 

Sorry for the incomplete error and no reproducing example. The complete output message was too lengthy to print out here. 

Anyways, It solved with updating R version to latest one.
