### ISSUE TITLE
Add BugReport: https://github.com/Bioconductor/AnnotationHub/issues (?)

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/AnnotationHub#18]
Just wanna suggest to add:
```
BugReport: https://github.com/Bioconductor/AnnotationHub/issues
```
to make it easier to find this page.  The only info on <http://bioconductor.org/packages/release/bioc/html/AnnotationHub.html> is the maintainer email address.

**Comment by lshep** [comment]
Description version Version: 2.21.4  in devel now includes the BugReports link.
