### ISSUE TITLE
Fetching RepeatMasker Files with AnnotationHub

### ISSUE THREAD

**Issue by mikecuoco** [Bioconductor/AnnotationHub#26]
I am hoping to integrate your great tool into my repetitive element analysis pipeline, but it seems like some  RepeatMasker files (hosted at UCSC) are missing from the cache. Namely, the hg38 repeatmasker file. Would it be possible to add `hgdownload.cse.ucsc.edu/goldenpath/hg38/database/rmsk.txt.gz` to the cache?

**Comment by lshep** [comment]
I apologize for the delayed response.  AnnotationHub is mosty a Bioconductor user contributed resource.  If you would like those included I suggest creating a package, or implementing in the package already in creation, to add the data to the hubs yourself.
