### ISSUE TITLE
QFeatures has been fixed

### ISSUE THREAD

**Issue by cvanderaa** [Bioconductor/AnnotationHub#29]
Hello, 

The exception that has been hardcoded for `QFeatures` objects should no longer be needed since `QFeatures>=1.5.2` (https://github.com/rformassspectrometry/QFeatures/commit/1558b0561b7997f1f222629180a5a3d02ff58d63).

cf https://github.com/Bioconductor/AnnotationHub/commit/add08877fc393b6270d0e33be960f6a8c9db5859

Sorry for the inconvenience.

**Comment by hpages** [comment]
Hardcoded exception removed in AnnotationHub 3.3.7 (commit 5f03a3c7e77530f02d0202556f808f3a6e766eb4). Thanks @cvanderaa.
