### ISSUE TITLE
AnnotationHub Update

### ISSUE THREAD

**Issue by gnatowskie** [Bioconductor/AnnotationHub#39]
Hello!

I have aligned and annotated my data with the mus musculus release version 108.  I'm currently working on a project that requires using annotation hub to query gtf files. When could I expect AnnotationHub to have query information on release-108? 

Thanks!
Emma

**Comment by lshep** [comment]
I will be working on scripts over the next week to add 108 and 109. Sorry for the inconvenience.

**Comment by lshep** [comment]
I have added the 108 and 109 gtf into the AnnotationHub.   2bit files will be delayed until at least next week.
