### ISSUE TITLE
dbplyr update is breaking AnnotationHub

### ISSUE THREAD

**Issue by mjsteinbaugh** [Bioconductor/AnnotationHub#46]
Hi Bioconductor team, I'm now seeing this error with the new dbplyr 2.4.0 update:

```
> packageVersion("AnnotationHub")
[1] ‘3.8.0’
> packageVersion("dbplyr")
[1] ‘2.4.0’
```

```
> AnnotationHub::AnnotationHub()
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Backtrace:
     ▆
  1. ├─AnnotationHub::AnnotationHub()
  2. │ └─AnnotationHub::.Hub(...)
  3. │   └─AnnotationHub:::.create_cache(...)
  4. │     └─BiocFileCache::BiocFileCache(cache = cache, ask = ask)
  5. │       └─BiocFileCache:::.sql_create_db(bfc)
  6. │         └─BiocFileCache:::.sql_validate_version(bfc)
  7. │           └─BiocFileCache:::.sql_schema_version(bfc)
  8. │             ├─base::tryCatch(...)
  9. │             │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 10. │             └─tbl(src, "metadata") %>% collect(Inf)
 11. ├─dplyr::collect(., Inf)
 12. └─dbplyr:::collect.tbl_sql(., Inf)
 13.   ├─base::tryCatch(...)
 14.   │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 15.   │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 16.   │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 17.   └─dbplyr::db_collect(x$src$con, sql, n = n, warn_incomplete = warn_incomplete, ...)
 18.     └─rlang (local) `<fn>`()
 19.       └─rlang:::check_dots(env, error, action, call)
 20.         └─rlang:::action_dots(...)
 21.           ├─base (local) try_dots(...)
 22.           └─rlang (local) action(...)
```

Best,
Mike

**Comment by lshep** [comment]
Please read annoucements and updates -- this is already taken care of 
https://support.bioconductor.org/p/9154865/
https://stat.ethz.ch/pipermail/bioc-devel/2023-October/020003.html

**Comment by mjsteinbaugh** [comment]
Thanks @lshep !

Fixed with BiocFileCache 2.11.1 in case anybody else sees this

**Comment by flying-sheep** [comment]
And 2.10.1, which is in the stable Bioconductor release and therefore probably more useful for most people.

**Comment by meganbkratz** [comment]
In case anyone is stuck in older R (4.1.1), I resolved this by downgrading dbplyr from 2.5.0 to 2.3.0

**Comment by paria90** [comment]
I STUCK!
Would anyone be able to help? I tried several ways which I found in the browser but none of them could solve it!

AH <- AnnotationHub()
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Run `rlang::last_trace()` to see where the error occurred.

**Comment by lshep** [comment]
What version of R and Bioconductor are you using?  Again there are pointers to how to resolve this in this thread

**Comment by paria90** [comment]
My R version is 4.2.2 and my Bioconductor version is 3.16. Based on the official Bioconductor announcement page lists compatibility,  For Bioconductor 3.16, the table confirms that it is compatible with R 4.2.x.

**Comment by paria90** [comment]
With this code, I could solve my problem:

devtools::install_github('https://github.com/Bioconductor/BiocFileCache.git')

for anyone who has the same problem :)
