### ISSUE TITLE
Vignette title vs name of Rmd file

### ISSUE THREAD

**Issue by hpages** [Bioconductor/AnnotationHub#48]
Could the error message:
```
Error: package or namespace load failed for ‘coMethDMR’:
 .onLoad failed in loadNamespace() for 'coMethDMR', details:
  call: NULL
  error: Corrupt Cache: index file
  See AnnotationHub's TroubleshootingTheCache vignette section on corrupt cache
  cache: /home/biocbuild/.cache/R/ExperimentHub
  filename: experimenthub.index.rds
Error: loading failed
Execution halted
ERROR: loading failed
```
use the title of the vignette ("Troubleshooting The Hubs") instead of the name of the Rmd or HTML file? This would make the vignette easier to find on [the package landing page](https://bioconductor.org/packages/AnnotationHub) where the former is displayed. Note that the former is also what gets displayed by `browseVignettes(package="AnnotationHub")`.

Ideally the title and Rmd file should be the same or very similar (e.g. `Troubleshooting_The_Hubs.Rmd`) to avoid confusion.

Thanks,
H.

P.S.: Looks like a leftover from #12

**Comment by lshep** [comment]
I can update the section to include the vignette title. I wanted to include the exact section that would be helpful too but was afraid the message would get too long?

**Comment by hpages** [comment]
AFAICT the message already indicates what section to look at ("section on corrupt cache"), so that part is fine. Thanks!
