### ISSUE TITLE
Error with sesameDataCatche

### ISSUE THREAD

**Issue by AndersJoergensen** [Bioconductor/AnnotationHub#50]
Hi Im trying to catche my data before working with sesame in R. 

Im using the sesameDataCache() command. 

But i get this error: 

Show in New Window
Error under evaluation of argument 'x' under emthod for function 'query': Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?

I have tried to update all packages related, but it does not seem to work. 
Any ideas as to how I can get this to work?
Thanks

**Comment by AndersJoergensen** [comment]
It works now

**Comment by lshep** [comment]
You likely needed to update to the current dbplyr and AnnotationHub version as this has been resolved in the updated packages
