### ISSUE TITLE
AnnotationHub and GO Terms

### ISSUE THREAD

**Issue by famfigueiredo** [Bioconductor/AnnotationHub#51]
As a follow up of this [question](https://github.com/Bioconductor/AnnotationHub/issues/27#issuecomment-1755963286), while I was able to replicate the analysis by using the same version of R and Bioconductor used at the time, I would like to understand the source of the discrepancies between using the AH107424 annotation file in 2022 and AH114250 in 2023.

The issue is that I do not get the same GO Terms through ```enrichGO``` with both annotation files. Since the AH114250 annotation file is quite recent, is it a question of the annotation with GO Terms 'catching up'?
Plotted in 2022 using older Atlantic salmon annotation file. Downregulated (A) vs Upregulated (B).
![ora_downreg_vs_upreg_4WPC](https://github.com/Bioconductor/AnnotationHub/assets/26144575/5e0b7a9c-b4c9-4052-833e-4ad3455af3d8)

Plotted in 2024 using more recent Atlantic salmon annotation file
![dnavaccine_vs_conu_4wpc_resized](https://github.com/Bioconductor/AnnotationHub/assets/26144575/9e9a7af0-5710-40e0-8dc6-391870ec3d05)

**Comment by lshep** [comment]
These types of questions are better asked on the [support site](support.bioconductor.org) and only report bugs or feature requests in issues.   We generate the objects based on data at ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/ .  You can look at the [README](https://ftp.ncbi.nlm.nih.gov/gene/DATA/README) to find out how these files are updated.
