### ISSUE TITLE
ah <- AnnotationHub() not working 

### ISSUE THREAD

**Issue by priya-naraypx1** [Bioconductor/AnnotationHub#57]
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Backtrace:
  1. AnnotationHub::AnnotationHub()
 12. dbplyr:::collect.tbl_sql(., Inf)
 14. dbplyr::db_collect(x$src$con, sql, n = n, warn_incomplete = warn_incomplete, ...)

R version : 4.3.0 and Annotation Hub version : 3.8.0

**Comment by lshep** [comment]
https://github.com/Bioconductor/AnnotationHub/issues/46
